config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "my_flights", to: "flights#my_flights", as: :my_flights
  root to: 'pages#home'
  resources :users, only: :show
  resources :flights
  resources :rockets do
    resources :flights, controller: 'rockets/flights'
  end
  resources :flights do
    resources :bookings, only: [:index, :show, :new, :create, :destroy]
  end


  resources :bookings, only: [:index, :show]
  patch 'flights/flights_id/bookings/:id', to: 'bookings#validates_user', as: :validates
  patch 'flights/flights_id/bookings/:id/refuses', to: 'bookings#refuses_user', as: :refuses

end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :rocket
  has_many :bookings, dependent: :destroy;
  validates :date, :destination, :departure, presence: true

  def self.search(search)
    flight = Flight.find_by(destination: search)
  end
end

app/controllers/flights_controller.rb
  class FlightsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:search].present?
      @flights = Flight.where("destination ILIKE :search OR departure ILIKE :search", search: "%#{params[:search]}%")
    else
      @flights = Flight.all
    end
  end

  def new
    @flight = Flight.new
  end

  def my_flights
    @flights = []
    Flight.all.each do |flight|
      @flights << flight if flight.rocket.user == current_user
    end
    return @flights
  end

  def create
    @flight = Flight.new(flight_params)
    @rocket = Rocket.find(flight_params[:rocket_id])
    @flight.rocket = @rocket
    if @flight.save
      respond_to do |format|
        format.html { redirect_to my_flights_path }
        format.js
      end
      # redirect_to bookings_path
    else
      respond_to do |format|
        format.html { render :new }
      end
      # render :new
    end
  end

  def destroy
    @flight = Flight.find(params[:id])
    if @flight.destroy
      respond_to do |format|
        format.html { redirect_to my_flights_path }
        format.js
      end
    end
    # redirect_to my_flights_path
  end

  def show
    @flight = Flight.find(params[:id])
  end

  private

  def flight_params
    params.require(:flight).permit(:description, :date, :departure, :destination, :rocket_id)
  end

end

app/controllers/rockets/flights_controller.rb
class Rockets::FlightsController < ApplicationController

  def new
    @rocket = Rocket.find(params[:rocket_id])
    @flight = Flight.new
  end

  def create
    @flight = Flight.new(flight_params)
    @rocket = Rocket.find(params[:rocket_id])
    @flight.rocket = @rocket
    if @flight.save
      respond_to do |format|
        format.html { redirect_to redirect_to my_flights_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
      end
      # render :new
    end
  end

private

  def flight_params
    params.require(:flight).permit(:description, :date, :departure, :destination, :rocket_id)
  end

end

app/views/flights/create.js.erb
displayInfo("Check ignition", "/my_flights", "Fasten your seatbelt", "success");

app/views/flights/destroy.js.erb
// displayInfo("Check ignition", "/flights/my_flights", "Are you sure?", "warning");
deleteInfo("/my_flights")

app/views/flights/index.html.erb
<div class="medium-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://source.unsplash.com/featured/?outerspace');">
  <div class="banner-content">
    <h1>Flights available</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="bills-all">
        <% if @flights.blank? %>
          <h4>Sorry, there are no flights matching to: <%= params[:search] %>.</h4>
        <% else %>

          <% @flights.each do |flight| %>
            <div class="col-xs-12">
              <div class="bills-and-button">
                <div class="col-xs-12">
                  <div class="bills-large">

                    <div class="bills-category">
                      <p>🚀 ROCKET MODEL: <%= flight.rocket.model.upcase %></p>
                    </div>

                    <div class="bills-description">
                      <ul>
                        <li><h4>🛫 <em>From</em><strong> <%= flight.departure %></strong></h4></li>
                        <li><h4>🛬 <em>To </em><strong><%= flight.destination %></strong></h4></li>
                        <li><p><em>Departing On</em><strong> <%= flight.date.strftime('%a %e %b %Y') %></strong></p></li>
                      </ul>
                    </div>

                    <%= cl_image_tag("#{flight.rocket.photo}", crop: :fill, class: "bill-user") %>
                    <a class="bills-link" href="/flights/<%= flight.id %>" ></a>
                  </div>
                </div>
                <%= link_to "Book", new_flight_booking_path(flight), class: 'bills-book-button' %>

              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flights/my_flights.html.erb
<div class="medium-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://source.unsplash.com/featured/?outerspace');">
  <div class="banner-content">
    <h1>Flights available</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="bills-all">
        <% if current_user.rockets.blank? %>
          <h4>You don't have a rocket yet. You need one to create a flight. <%= link_to "Add a Rocket", new_rocket_path, class: "btn btn-primary" %></h4>
        <% elsif @flights.blank? %>
          <h4>You don't have proposed a flight yet. <%= link_to "Propose one", new_flight_path, class: "btn btn-primary" %></h4>
        <% else %>

          <% @flights.each do |flight| %>
            <div class="col-xs-12">
              <div class="bills-and-button">
                <div class="col-xs-12">
                  <div class="bills-large">

                    <div class="bills-category">
                      <p>🚀 ROCKET MODEL: <%= flight.rocket.model.upcase %></p>
                    </div>

                    <div class="bills-description">
                      <ul>
                        <li><h4>🛫 <em>From</em><strong> <%= flight.departure %></strong></h4></li>
                        <li><h4>🛬 <em>To </em><strong><%= flight.destination %></strong></h4></li>
                        <li><p><em>Departing On</em><strong> <%= flight.date.strftime('%a %e %b %Y') %></strong></p></li>
                      </ul>
                    </div>

                    <%= cl_image_tag("#{flight.rocket.user.photo}", crop: :fill, class: "bill-user") %>
                    <a class="bills-link" href="/flights/<%= flight.id %>" ></a>
                  </div>
                </div>
                <%= link_to "Cancel", flight_path(flight), method: :delete, remote: true, class: 'bills-book-button bills-cancel-button' %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flights/new.html.erb
<div class="background-img" style="  background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://images.unsplash.com/photo-1465788786008-f75a725b34e9?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e088ec671a9d481a27a8b2c8b7c07d82&auto=format&fit=crop&w=1050&q=80');">

  <div class="form">

    <div class="form-title">
      <h1>Create a flight</h1>
    </div>
    <div class="form-table sweet-alert" data-flight-id="1">
      <%= simple_form_for @flight, remote: true do |f| %>
        <%= f.input :destination, placeholder: 'Enter your destination' %>
        <%= f.input :departure, placeholder: 'Enter your departure location' %>
        <%= f.input :description, placeholder: 'Enter some description for your flight' %>
        <%= f.association :rocket, collection: current_user.rockets.map(&:name_and_model_for_new),include_blank: false %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"}, placeholder: 'Select a date' %>
        <%= f.button :submit, class: 'btn-form' %>
      <% end %>
    </div>

  </div>
</div>

<!-- USED TO HAVE html5: true WITHIN f.INPUT : DATE -->

app/views/flights/show.html.erb
<div class="medium-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://source.unsplash.com/featured/?outerspace');">
  <div class="banner-content">
    <h1>Your flight details</h1>
  </div>
</div>


<div class="container">
      <div class="profile text-center">
        <div class="main">
          <div class="main-content">
             <%= cl_image_tag @flight.rocket.user.photo, height: 100, width: 110, crop: :thumb, gravity: :face, class: "img-circle", alt: "no profile_pic" %>
            <h2> <strong> <%= @flight.rocket.user.name %></strong></h2>
            <p>Stardriver</p>
            <strong>More about <%= link_to @flight.rocket.user.name, @flight.rocket.user %></strong>
            <%= link_to "Book this now", new_flight_booking_path(@flight), class: 'btn' %>
          </div>
        </div>
        <div class="stat">
          <h2><strong><%= @flight.date.strftime('%a %e %b %Y') %></strong>
          <h2><em>From:</em> <strong><%= @flight.departure %></strong><em> To:</em> <strong><%= @flight.destination %></strong></h2>
        </div>
        <div class="description">
          <div class="description-content">
            <h3><strong>More About this flight</strong></h3>
            <p>With the <strong><%= @flight.rocket.name %></strong> a <%= @flight.rocket.model %></p>
            <p class="text-justify">
              <%=@flight.description %> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, molestias, cum, veritatis facere incidunt eaque quisquam rerum nulla temporibus aliquid architecto debitis eius fugit quos voluptates aut repellat fuga autem!
            </p>
            <%= cl_image_tag("#{@flight.rocket.photo}", crop: :fill, class: "profile-rocket-avatar") %>
            <h3></h3>
          </div>
        </div>
      </div>
    </div>