config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "my_flights", to: "flights#my_flights", as: :my_flights
  root to: 'pages#home'
  resources :users, only: :show
  resources :flights
  resources :rockets do
    resources :flights, controller: 'rockets/flights'
  end
  resources :flights do
    resources :bookings, only: [:index, :show, :new, :create, :destroy]
  end


  resources :bookings, only: [:index, :show]
  patch 'flights/flights_id/bookings/:id', to: 'bookings#validates_user', as: :validates
  patch 'flights/flights_id/bookings/:id/refuses', to: 'bookings#refuses_user', as: :refuses

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flight
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user_id: current_user)
    @meflights = []
    Flight.all.each do |flight|
      @meflights << flight if flight.rocket.user == current_user
    end
    @mepilot = []
    Booking.all.each do |booking|
      @mepilot << booking if booking.flight.rocket.user == current_user
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new

  end

  def create
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new(booking_params)
    @booking.status = "Pending"
    @booking.flight = @flight
    @booking.user = current_user
    if @booking.save
      respond_to do |format|
        format.html { redirect_to bookings_path }
        format.js
      end
      # redirect_to bookings_path
    else
      respond_to do |format|
        format.html { render :new }
      end
      # render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      respond_to do |format|
        format.html { redirect_to bookings_path }
        format.js
      end
    end
  end

  # CHANGED TO VALIDATE USER DIRECTLY FROM INDEX
  def validates_user
    @booking = Booking.find(params[:id])
    @booking.status = "Accepted"
    @booking.save
    redirect_to bookings_path
  end

  # NOT IN USE
  def refuses_user
    @booking = Booking.find(params[:id])
    @booking.status = "Declined"
    @booking.save
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:comments)
  end

end

app/views/bookings/create.js.erb
displayInfo("Fasten your seatbelt", "/bookings", "May god be with you", "success");

app/views/bookings/destroy.js.erb
deleteInfo("bookings")

app/views/bookings/index.html.erb
<div class="medium-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1503751071777-d2918b21bbd9?ixlib=rb-0.3.5&s=cf09e49d47f6513c52cff126d013d2a8&auto=format&fit=crop&w=1050&q=80');">
  <div class="banner-content">
    <h1>Your next bookings</h1>
  </div>
</div>

<div class="messages-content">
  <div class="travelers">
    <div class="title-box">
      <h2>Your bookings as a traveler</h2>
    </div>

    <div class="message-box">
      <% @bookings.each do |booking| %>
        <div class="small-message">

          <div class="small-message-infos">

            <div class="small-message-details">
              <p><em>🛫 From: &emsp;</em><strong><%= booking.flight.departure %></strong> &emsp;<em>🛬 To:&emsp;</em><strong><%= booking.flight.destination %></strong></p>

            </div>

            <div class="small-message-date">
              <p><em>Date:&emsp;</em><strong><%= booking.flight.date.strftime('%a %e %b %Y') %></strong></p>
            </div>

            <div class="small-message-rocket">
              <p><strong>🚀 : <%= booking.flight.rocket.name %></strong></p>
              <p><em>Rocket Model:<%= booking.flight.rocket.model %></em></p>
              <p><em>Pilot:<%= booking.flight.rocket.user.name %> </em></p>
            </div>
          </div>

          <div class="grid-btns">
            <div class="status">
              <p><strong><%= booking.status %></strong></p>

            </div>
              <%= link_to "Cancel", flight_booking_path(booking.flight, booking), method: :delete, remote: true, class: 'btn-cancels' %>
              <%= link_to "See details", booking_path(booking), class: 'btn-details' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <% if current_user.rockets %>
    <div class="pilots">
      <div class="title-box">
        <h2>Your bookings as a pilot</h2>
      </div>
      <ul class="nav nav-tabs" role="tablist">
        <% @meflights.each do |flight| %>

          <li role="presentation" class="active"><a href="#" aria-controls="<%= flight.id %>" role="tab" data-toggle="tab">Flight: <%= flight.id %></a>
          </li>
        <% end %>
      </ul>
      <% @meflights %>
      <% @meflights.each do |flight| %>
        <% flight.bookings.each do |booking| %>
        <% if booking.flight.rocket.user.id == current_user.id && booking.status != "Denied"%>
          <div class="small-message">

            <div class="small-message-infos">

              <div class="small-message-details">
                <p><em>🛫 From: &emsp;</em><strong><%= booking.flight.departure %></strong> &emsp;<em>🛬 To:&emsp;</em><strong><%= booking.flight.destination %></strong></p>
              </div>

              <div class="small-message-date">
                <p><em>Date:&emsp;</em><strong><%= booking.flight.date.strftime('%a %e %b %Y') %></strong></p>
              </div>

              <div class="small-message-rocket">
                <p><strong>🚀 : <%= booking.flight.rocket.name %></strong></p>
                <p><em>Rocket Model:<%= booking.flight.rocket.model %></em></p>
                <p><em>Pilot:<%= booking.flight.rocket.user.name %> </em></p>
              </div>
            </div>

            <div class="grid-btns">
              <div class="status">
                <p><strong><%= booking.status %></strong></p>
              </div>
                <% if booking.status == "Accepted" %>
                  <%= link_to 'Cancel', refuses_path(booking), method: :patch, class: 'btn-cancels' %>
                <% else %>
                   <%= link_to 'Accept', validates_path(booking), method: :patch, class: 'btn-validates' %>
                    <%= link_to 'Refuse', refuses_path(booking), method: :patch, class: 'btn-refuses' %>
                <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="background-img" style="  background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://images.unsplash.com/photo-1522760122564-d567dac67f45?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=72db790ed87aa5e39abbb4e336e42284&auto=format&fit=crop&w=975&q=80');">

  <div class="form">

    <div class="form-title">
      <h1>Confirm your booking</h1>
    </div>
    <div class="form-subtitle">
      <div class="form-flight-info">
        <h2>Your flight details:</h2>

        <p>🛫 Departing from:</p>
        <h4><%= @flight.departure %></h4>

        <p>🛬 Arriving in:</p>
        <h4><%= @flight.destination %></h4>

        <p>Flight Date:</p>
        <h4><%= @flight.date.strftime('%a %e %b %Y') %></h4>

      </div>

      <div class="form-additional-info">
        <h5>Additional details:</h5>
        <p>🚀 Rocket type: <%= @flight.rocket.model %></p>

        <p>Number of passengers: <%= @flight.rocket.capacity %></p>
        <!-- <p>Pilot: </p> -->
        <p>Additional details: <%= @flight.description %></p>
      </div>

    </div>

    <div class="form-table">
        <%= simple_form_for [@flight, @booking], remote: true do |f| %>
          <%= f.input :comments, placeholder: 'Let us know of any information you wish to share with us' %>
          <%= f.button :submit,class: 'btn-form' %>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="medium-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1457979406492-d1e6b97f3f55?ixlib=rb-0.3.5&s=df633aa537ab522c5e97ccae06fa3ad8&auto=format&fit=crop&w=1050&q=80');">
  <div class="banner-content">
    <h1>Booking details</h1>
  </div>
</div>

<div class="container">
  <% if current_user == @booking.flight.rocket.user %>
    <div class="message">
      <div class="message-name">
        <h2>Departure date</h2>
        <h3><%= @booking.flight.date.strftime('%a %e %b %Y') %></h3>
      </div>
      <div class="message-body">
        <h2>🛫 <%= @booking.flight.departure %></h2>
        <h2>🛬 <%= @booking.flight.destination %></h2>
        <p>Booking reference: <%= @booking.id %></p>
      </div>
      <div class="message-body">
        <h2>🚀 : <%= @booking.flight.rocket.name %></h2>
        <p>Model: <%= @booking.flight.rocket.model %></p>
        <h3>Pilot: <%= @booking.flight.rocket.user.name %></h3>

      </div>
      <div class="message-status">
        <div class="grid-btns">
          <h3 class="status"><%= @booking.status %></h3>
          <div class="btn-cancels">
            <%= link_to "Cancel", flight_booking_path(@booking.flight, @booking), method: :delete, class: 'btn btn-danger', data: {confirm: "are you sure you want to delete this booking?"} %>
          </div>
        </div>
      </div>
    </div>
  <% elsif current_user == @booking.user %>
    <div class="message-details">
      <div class="message-body">
        <h2>Departure date</h2>
        <h3><%= @booking.flight.date.strftime('%a %e %b %Y') %></h3>
      </div>
      <div class="message-body">
        <h2>🛫 <%= @booking.flight.departure %></h2>
        <h2>🛬 <%= @booking.flight.destination %></h2>
        <p>Booking reference: <%= @booking.id %></p>
      </div>
      <div class="message-status message-body">
        <h2 class="status">Status: <%= @booking.status %></h2>
      </div>
    </div>
    <div class="message">
      <div class="message-body">
        <h2>🚀 : <%= @booking.flight.rocket.name %></h2>
        <p>Model: <%= @booking.flight.rocket.model %></p>
        <%= cl_image_tag("#{@booking.flight.rocket.photo}",
              crop: :fill, class: "rocket-pic-booking") %>
      </div>
      <div class="message-body">
        <h3>Pilot: <%= @booking.flight.rocket.user.name %></h3>
      </div>
      <div class="message-body">
        <p>Comments: <%= @booking.comments %></p>
      </div>


    </div>
  <% end %>


  <%= link_to "Check flight offer", flight_path(@booking.flight), class: 'btn-primary' %>

</div>