config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "my_flights", to: "flights#my_flights", as: :my_flights
  root to: 'pages#home'
  resources :users, only: :show
  resources :flights
  resources :rockets do
    resources :flights, controller: 'rockets/flights'
  end
  resources :flights do
    resources :bookings, only: [:index, :show, :new, :create, :destroy]
  end


  resources :bookings, only: [:index, :show]
  patch 'flights/flights_id/bookings/:id', to: 'bookings#validates_user', as: :validates
  patch 'flights/flights_id/bookings/:id/refuses', to: 'bookings#refuses_user', as: :refuses

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :rockets
  has_many :bookings
  mount_uploader :photo, PhotoUploader

  def rockets_display
    str = ""
    if self.rockets?
      self.rockets.each do |rocket|
        str += "A model #{rocket.model} with #{rocket.capacity} sits."
      end
    else
      str = "You don't have a rocket yet."
    end
    return str
  end

  def rockets?
    self.rockets != nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/views/users/show.html.erb
 <div class="medium-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://source.unsplash.com/featured/?outerspace');">
  <div class="banner-content">
    <h1>Your profile</h1>
  </div>
</div>
<div class="container">
  <div class="profile text-center">
    <div class="main">
      <div class="main-content">
        <%= cl_image_tag current_user.photo, class: "img-circle" %>
          <h2> <strong><%= current_user.name %></strong></h2>
          <h3><strong><%= current_user.email %></strong></h3>
      </div>
    </div>
  <div class="stat">
    <h3><strong>Rockets:</strong></h3>
      <% unless current_user.rockets %>
        You don't have a rocket yet. <%= link_to "Add one", new_rocket_path %>
      <% end %>
    </p>
      <ul>
        <% current_user.rockets.each do |rocket| %>
          <li>Model : <%= rocket.model %>, with <%= rocket.capacity %> sits.
            <% if policy(rocket).destroy? %>
              <%= link_to "Delete", rocket_path(rocket)  , method: :delete, data: {confirm: "are you sure you want to delete this rocket? This will destroy all the flights you planned with it aswell"} %>
            <% end %>
          </p>
            <% if policy(rocket).update? %>
              <%= link_to "Modify", edit_rocket_path(rocket) %>
            <% end %>
              </li>
        <% end %>
      </ul>
      <a class="btn btn-success" href="/rockets/new">Add a rocket</a>
  </div>
  <div class="description">
            <div class="description-content">
              <h3><strong>More about Me</strong></h3>
              <p class="text-justify">
               <%= current_user.bio %>
              </p>
              <a class="btn btn-success" href="/users/edit">Edit my profile</a>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>