config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "my_flights", to: "flights#my_flights", as: :my_flights
  root to: 'pages#home'
  resources :users, only: :show
  resources :flights
  resources :rockets do
    resources :flights, controller: 'rockets/flights'
  end
  resources :flights do
    resources :bookings, only: [:index, :show, :new, :create, :destroy]
  end


  resources :bookings, only: [:index, :show]
  patch 'flights/flights_id/bookings/:id', to: 'bookings#validates_user', as: :validates
  patch 'flights/flights_id/bookings/:id/refuses', to: 'bookings#refuses_user', as: :refuses

end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook-square"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Stardrivers is made with <i class="fa fa-heart"></i> by the Shinier Team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <div class="reload">
    <%= image_tag "ok.gif", height: 70 %>
  </div>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <% if current_user.rockets %>
        <%= link_to "My flights", my_flights_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <%= link_to "All flights", flights_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Add a rocket 🚀", new_rocket_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% if current_user.rockets.exists? %>
      <%= link_to "Add a flight", new_flight_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, height: 300, width: 400, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Register", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="/flights">Flights</a></li>
      </ul>
    </div>
  </div>
</div>